name: AIM Digital
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5546730195637792
title: AIM Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#336799'
    - '#fec107'
    - '#ff6600'
    - '#000000'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.6040037747006863
purpose: []
