name: AIM Digital
favicon: null
layout_spectrum: 0.6640383386984468
typography_spectrum: 0.5546730195637792
title: AIM Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#336799'
    - '#fec107'
    - '#ff6600'
    - '#000000'
  brandStrength: 0.9231876914855093
  lightness: 0.2188181143719703
  saturation: 0.25
  rhythmicContrast: 0.6040037747006863
purpose: []
